#!/usr/bin/env bash

export EDITOR=vim

alias rlsh="source $HOME/.bashrc"

# gentoo aliases
alias eix="eix --color never"

PATH=$PATH:~/.local/bin
PATH=$PATH:~/.cargo/bin

# Misc aliases
alias cdd="cd $HOME/code"
alias grep="rg"

# AWS bits
sap() {
    local aws_prof=$(grep profile ~/.aws/config | cut -d ' ' -f 2 | cut -d ']' -f 1 | fzf)
    if [[ -n "$aws_prof" ]]; then
	export AWS_PROFILE=$aws_prof
    fi
}

# AWS aliases
alias sapu="unset AWS_PROFILE"
alias saru="unset AWS_REGION"
alias sapu="unset AWS_PROFILE"

# interactive ssh prompt
jump() {
    local server=$(grep -i "host " ~/.ssh/config | cut -d ' ' -f 2 | fzf)
    if [[ -n "$server" ]]; then
	ssh $server
    fi
}
